// <auto-generated />
namespace ERPDAL.ControlPanelContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ControlPaneltblRole : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ControlPaneltblRole));
        
        string IMigrationMetadata.Id
        {
            get { return "202003280522254_ControlPaneltblRole"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
